/**
 * UGENE - Integrated Bioinformatics Tools.
 * Copyright (C) 2008-2021 UniPro <ugene@unipro.ru>
 * http://ugene.net
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

#ifndef _U2_GT_TESTS_REGRESSION_SCENARIOS_7001_8000_H_
#define _U2_GT_TESTS_REGRESSION_SCENARIOS_7001_8000_H_

#include <harness/UGUITestBase.h>

namespace U2 {

namespace GUITest_regression_scenarios {

#undef GUI_TEST_SUITE
#define GUI_TEST_SUITE "GUITest_regression_scenarios"

GUI_TEST_CLASS_DECLARATION(test_7003)
GUI_TEST_CLASS_DECLARATION(test_7014)
GUI_TEST_CLASS_DECLARATION(test_7022)
GUI_TEST_CLASS_DECLARATION(test_7043)
GUI_TEST_CLASS_DECLARATION(test_7044)
GUI_TEST_CLASS_DECLARATION(test_7045)
GUI_TEST_CLASS_DECLARATION(test_7091)

GUI_TEST_CLASS_DECLARATION(test_7106)
GUI_TEST_CLASS_DECLARATION(test_7125)
GUI_TEST_CLASS_DECLARATION(test_7127)
GUI_TEST_CLASS_DECLARATION(test_7151)
GUI_TEST_CLASS_DECLARATION(test_7152)
GUI_TEST_CLASS_DECLARATION(test_7183)
GUI_TEST_CLASS_DECLARATION(test_7193_1)
GUI_TEST_CLASS_DECLARATION(test_7193_2)

GUI_TEST_CLASS_DECLARATION(test_7212)
GUI_TEST_CLASS_DECLARATION(test_7234)
GUI_TEST_CLASS_DECLARATION(test_7246)
GUI_TEST_CLASS_DECLARATION(test_7247)
GUI_TEST_CLASS_DECLARATION(test_7293)

#ifdef SW2_BUILD_WITH_CUDA
GUI_TEST_CLASS_DECLARATION(test_7360)
#endif  // SW2_BUILD_WITH_CUDA
GUI_TEST_CLASS_DECLARATION(test_7367)
GUI_TEST_CLASS_DECLARATION(test_7368)
GUI_TEST_CLASS_DECLARATION(test_7371)
GUI_TEST_CLASS_DECLARATION(test_7380)
GUI_TEST_CLASS_DECLARATION(test_7384_1)
GUI_TEST_CLASS_DECLARATION(test_7384_2)
GUI_TEST_CLASS_DECLARATION(test_7388)
GUI_TEST_CLASS_DECLARATION(test_7390)

GUI_TEST_CLASS_DECLARATION(test_7401)
GUI_TEST_CLASS_DECLARATION(test_7403)
GUI_TEST_CLASS_DECLARATION(test_7404_1)
GUI_TEST_CLASS_DECLARATION(test_7404_2)
GUI_TEST_CLASS_DECLARATION(test_7405)
GUI_TEST_CLASS_DECLARATION(test_7407)
GUI_TEST_CLASS_DECLARATION(test_7414)
GUI_TEST_CLASS_DECLARATION(test_7415_1)
GUI_TEST_CLASS_DECLARATION(test_7415_2)
GUI_TEST_CLASS_DECLARATION(test_7415_3)
GUI_TEST_CLASS_DECLARATION(test_7438)
GUI_TEST_CLASS_DECLARATION(test_7447)
GUI_TEST_CLASS_DECLARATION(test_7451)
GUI_TEST_CLASS_DECLARATION(test_7456)
GUI_TEST_CLASS_DECLARATION(test_7460)
GUI_TEST_CLASS_DECLARATION(test_7469)

#undef GUI_TEST_SUITE

}  // namespace GUITest_regression_scenarios

}  // namespace U2

#endif  // _U2_GT_TESTS_REGRESSION_SCENARIOS_7001_8000_H_
