/**
 * UGENE - Integrated Bioinformatics Tools.
 * Copyright (C) 2008-2017 UniPro <ugene@unipro.ru>
 * http://ugene.net
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

#ifndef _U2_GT_TESTS_REGRESSION_SCENARIOS_5001_6000_H_
#define _U2_GT_TESTS_REGRESSION_SCENARIOS_5001_6000_H_

#include <U2Test/UGUITestBase.h>

namespace U2 {

namespace GUITest_regression_scenarios {

#undef GUI_TEST_SUITE
#define GUI_TEST_SUITE "GUITest_regression_scenarios"

GUI_TEST_CLASS_DECLARATION(test_5004)
GUI_TEST_CLASS_DECLARATION(test_5012)
GUI_TEST_CLASS_DECLARATION(test_5012_1)
GUI_TEST_CLASS_DECLARATION(test_5012_2)
GUI_TEST_CLASS_DECLARATION(test_5018)
GUI_TEST_CLASS_DECLARATION(test_5027_1)
GUI_TEST_CLASS_DECLARATION(test_5027_2)
GUI_TEST_CLASS_DECLARATION(test_5029)
GUI_TEST_CLASS_DECLARATION(test_5039)
GUI_TEST_CLASS_DECLARATION(test_5052)
GUI_TEST_CLASS_DECLARATION(test_5069)
GUI_TEST_CLASS_DECLARATION(test_5082)
GUI_TEST_CLASS_DECLARATION(test_5090)

GUI_TEST_CLASS_DECLARATION(test_5128)
GUI_TEST_CLASS_DECLARATION(test_5137)
GUI_TEST_CLASS_DECLARATION(test_5138_1)
GUI_TEST_CLASS_DECLARATION(test_5138_2)
GUI_TEST_CLASS_DECLARATION(test_5199)

GUI_TEST_CLASS_DECLARATION(test_5208)
GUI_TEST_CLASS_DECLARATION(test_5216)
GUI_TEST_CLASS_DECLARATION(test_5227)
GUI_TEST_CLASS_DECLARATION(test_5246)
GUI_TEST_CLASS_DECLARATION(test_5249)
GUI_TEST_CLASS_DECLARATION(test_5252)
GUI_TEST_CLASS_DECLARATION(test_5268)
GUI_TEST_CLASS_DECLARATION(test_5278)
GUI_TEST_CLASS_DECLARATION(test_5295)

GUI_TEST_CLASS_DECLARATION(test_5314)
GUI_TEST_CLASS_DECLARATION(test_5346)
GUI_TEST_CLASS_DECLARATION(test_5352)
GUI_TEST_CLASS_DECLARATION(test_5356)
GUI_TEST_CLASS_DECLARATION(test_5360)
GUI_TEST_CLASS_DECLARATION(test_5363_1)
GUI_TEST_CLASS_DECLARATION(test_5363_2)
GUI_TEST_CLASS_DECLARATION(test_5367)
GUI_TEST_CLASS_DECLARATION(test_5371)
GUI_TEST_CLASS_DECLARATION(test_5377)

GUI_TEST_CLASS_DECLARATION(test_5412)
GUI_TEST_CLASS_DECLARATION(test_5417)
GUI_TEST_CLASS_DECLARATION(test_5425)
GUI_TEST_CLASS_DECLARATION(test_5469)
GUI_TEST_CLASS_DECLARATION(test_5499)

GUI_TEST_CLASS_DECLARATION(test_5517)

GUI_TEST_CLASS_DECLARATION(test_5520_1)
GUI_TEST_CLASS_DECLARATION(test_5520_2)
GUI_TEST_CLASS_DECLARATION(test_5562_1)
GUI_TEST_CLASS_DECLARATION(test_5562_2)
GUI_TEST_CLASS_DECLARATION(test_5562_3)
GUI_TEST_CLASS_DECLARATION(test_5588)

#undef GUI_TEST_SUITE

}   // namespace GUITest_regression_scenarios

}   // namespace U2

#endif // _U2_GT_TESTS_REGRESSION_SCENARIOS_5001_6000_H_
