/**
 * UGENE - Integrated Bioinformatics Tools.
 * Copyright (C) 2008-2023 UniPro <ugene@unipro.ru>
 * http://ugene.net
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

#pragma once

#include <harness/UGUITestBase.h>

namespace U2 {

namespace GUITest_regression_scenarios {

#undef GUI_TEST_SUITE
#define GUI_TEST_SUITE "GUITest_regression_scenarios"

GUI_TEST_CLASS_DECLARATION(test_7003)
GUI_TEST_CLASS_DECLARATION(test_7012)
GUI_TEST_CLASS_DECLARATION(test_7014)
GUI_TEST_CLASS_DECLARATION(test_7022)
GUI_TEST_CLASS_DECLARATION(test_7043)
GUI_TEST_CLASS_DECLARATION(test_7044)
GUI_TEST_CLASS_DECLARATION(test_7045)
GUI_TEST_CLASS_DECLARATION(test_7091)

GUI_TEST_CLASS_DECLARATION(test_7106)
GUI_TEST_CLASS_DECLARATION(test_7125)
GUI_TEST_CLASS_DECLARATION(test_7126)
GUI_TEST_CLASS_DECLARATION(test_7127)
GUI_TEST_CLASS_DECLARATION(test_7128)
GUI_TEST_CLASS_DECLARATION(test_7151)
GUI_TEST_CLASS_DECLARATION(test_7152)
GUI_TEST_CLASS_DECLARATION(test_7154)
GUI_TEST_CLASS_DECLARATION(test_7161)
GUI_TEST_CLASS_DECLARATION(test_7183)
GUI_TEST_CLASS_DECLARATION(test_7191)
GUI_TEST_CLASS_DECLARATION(test_7193)

GUI_TEST_CLASS_DECLARATION(test_7212)
GUI_TEST_CLASS_DECLARATION(test_7234)
GUI_TEST_CLASS_DECLARATION(test_7246)
GUI_TEST_CLASS_DECLARATION(test_7247)
GUI_TEST_CLASS_DECLARATION(test_7276)
GUI_TEST_CLASS_DECLARATION(test_7279)
GUI_TEST_CLASS_DECLARATION(test_7293)

GUI_TEST_CLASS_DECLARATION(test_7338)
GUI_TEST_CLASS_DECLARATION(test_7367)
GUI_TEST_CLASS_DECLARATION(test_7368)
GUI_TEST_CLASS_DECLARATION(test_7371)
GUI_TEST_CLASS_DECLARATION(test_7380)
GUI_TEST_CLASS_DECLARATION(test_7384_1)
GUI_TEST_CLASS_DECLARATION(test_7384_2)
GUI_TEST_CLASS_DECLARATION(test_7388)
GUI_TEST_CLASS_DECLARATION(test_7390)

GUI_TEST_CLASS_DECLARATION(test_7401)
GUI_TEST_CLASS_DECLARATION(test_7402)
GUI_TEST_CLASS_DECLARATION(test_7403)
GUI_TEST_CLASS_DECLARATION(test_7404_1)
GUI_TEST_CLASS_DECLARATION(test_7404_2)
GUI_TEST_CLASS_DECLARATION(test_7405)
GUI_TEST_CLASS_DECLARATION(test_7407)
GUI_TEST_CLASS_DECLARATION(test_7410)
GUI_TEST_CLASS_DECLARATION(test_7413)
GUI_TEST_CLASS_DECLARATION(test_7414)
GUI_TEST_CLASS_DECLARATION(test_7415_1)
GUI_TEST_CLASS_DECLARATION(test_7415_2)
GUI_TEST_CLASS_DECLARATION(test_7415_3)
GUI_TEST_CLASS_DECLARATION(test_7419);
GUI_TEST_CLASS_DECLARATION(test_7438)
GUI_TEST_CLASS_DECLARATION(test_7447)
GUI_TEST_CLASS_DECLARATION(test_7448_1)
GUI_TEST_CLASS_DECLARATION(test_7448_2)
GUI_TEST_CLASS_DECLARATION(test_7448_3)
GUI_TEST_CLASS_DECLARATION(test_7448_4)
GUI_TEST_CLASS_DECLARATION(test_7451)
GUI_TEST_CLASS_DECLARATION(test_7454)
GUI_TEST_CLASS_DECLARATION(test_7455)
GUI_TEST_CLASS_DECLARATION(test_7456)
GUI_TEST_CLASS_DECLARATION(test_7459)
GUI_TEST_CLASS_DECLARATION(test_7460)
GUI_TEST_CLASS_DECLARATION(test_7463)
GUI_TEST_CLASS_DECLARATION(test_7465)
GUI_TEST_CLASS_DECLARATION(test_7469)
GUI_TEST_CLASS_DECLARATION(test_7472)
GUI_TEST_CLASS_DECLARATION(test_7473_1)
GUI_TEST_CLASS_DECLARATION(test_7473_2)
GUI_TEST_CLASS_DECLARATION(test_7476)
GUI_TEST_CLASS_DECLARATION(test_7487_1)
GUI_TEST_CLASS_DECLARATION(test_7487_2)
GUI_TEST_CLASS_DECLARATION(test_7490)
GUI_TEST_CLASS_DECLARATION(test_7491)
GUI_TEST_CLASS_DECLARATION(test_7499)

GUI_TEST_CLASS_DECLARATION(test_7504)
GUI_TEST_CLASS_DECLARATION(test_7505)
GUI_TEST_CLASS_DECLARATION(test_7506)
GUI_TEST_CLASS_DECLARATION(test_7507)
GUI_TEST_CLASS_DECLARATION(test_7508)
GUI_TEST_CLASS_DECLARATION(test_7509)
GUI_TEST_CLASS_DECLARATION(test_7511)
GUI_TEST_CLASS_DECLARATION(test_7515)
GUI_TEST_CLASS_DECLARATION(test_7517)
GUI_TEST_CLASS_DECLARATION(test_7520)
GUI_TEST_CLASS_DECLARATION(test_7521)
GUI_TEST_CLASS_DECLARATION(test_7531)
GUI_TEST_CLASS_DECLARATION(test_7535)
GUI_TEST_CLASS_DECLARATION(test_7539)
GUI_TEST_CLASS_DECLARATION(test_7540)
GUI_TEST_CLASS_DECLARATION(test_7546)
GUI_TEST_CLASS_DECLARATION(test_7548)
GUI_TEST_CLASS_DECLARATION(test_7550)
GUI_TEST_CLASS_DECLARATION(test_7555)
GUI_TEST_CLASS_DECLARATION(test_7556)
GUI_TEST_CLASS_DECLARATION(test_7572)
GUI_TEST_CLASS_DECLARATION(test_7573)
GUI_TEST_CLASS_DECLARATION(test_7574)
GUI_TEST_CLASS_DECLARATION(test_7575)
GUI_TEST_CLASS_DECLARATION(test_7576)
GUI_TEST_CLASS_DECLARATION(test_7582)
GUI_TEST_CLASS_DECLARATION(test_7584)

GUI_TEST_CLASS_DECLARATION(test_7607)
GUI_TEST_CLASS_DECLARATION(test_7609)
GUI_TEST_CLASS_DECLARATION(test_7611)
GUI_TEST_CLASS_DECLARATION(test_7616)
GUI_TEST_CLASS_DECLARATION(test_7617)
GUI_TEST_CLASS_DECLARATION(test_7623)
GUI_TEST_CLASS_DECLARATION(test_7629)
GUI_TEST_CLASS_DECLARATION(test_7630)
GUI_TEST_CLASS_DECLARATION(test_7631)
GUI_TEST_CLASS_DECLARATION(test_7635)
GUI_TEST_CLASS_DECLARATION(test_7644)
GUI_TEST_CLASS_DECLARATION(test_7645)
GUI_TEST_CLASS_DECLARATION(test_7650)
GUI_TEST_CLASS_DECLARATION(test_7652)
GUI_TEST_CLASS_DECLARATION(test_7659)
GUI_TEST_CLASS_DECLARATION(test_7661)
GUI_TEST_CLASS_DECLARATION(test_7667_1)
GUI_TEST_CLASS_DECLARATION(test_7667_2)
GUI_TEST_CLASS_DECLARATION(test_7668)
GUI_TEST_CLASS_DECLARATION(test_7671)
GUI_TEST_CLASS_DECLARATION(test_7680)
GUI_TEST_CLASS_DECLARATION(test_7682)
GUI_TEST_CLASS_DECLARATION(test_7686)
GUI_TEST_CLASS_DECLARATION(test_7697)

GUI_TEST_CLASS_DECLARATION(test_7712)
GUI_TEST_CLASS_DECLARATION(test_7714)
GUI_TEST_CLASS_DECLARATION(test_7715)
GUI_TEST_CLASS_DECLARATION(test_7720)
GUI_TEST_CLASS_DECLARATION(test_7740)
GUI_TEST_CLASS_DECLARATION(test_7744)
GUI_TEST_CLASS_DECLARATION(test_7748)
GUI_TEST_CLASS_DECLARATION(test_7751)
GUI_TEST_CLASS_DECLARATION(test_7753)
GUI_TEST_CLASS_DECLARATION(test_7770)
GUI_TEST_CLASS_DECLARATION(test_7781)
GUI_TEST_CLASS_DECLARATION(test_7789)
GUI_TEST_CLASS_DECLARATION(test_7792)
GUI_TEST_CLASS_DECLARATION(test_7797)

GUI_TEST_CLASS_DECLARATION(test_7806)
GUI_TEST_CLASS_DECLARATION(test_7824)
GUI_TEST_CLASS_DECLARATION(test_7825)
GUI_TEST_CLASS_DECLARATION(test_7827)
GUI_TEST_CLASS_DECLARATION(test_7830)
GUI_TEST_CLASS_DECLARATION(test_7842)
GUI_TEST_CLASS_DECLARATION(test_7850)
GUI_TEST_CLASS_DECLARATION(test_7852)
GUI_TEST_CLASS_DECLARATION(test_7860)
GUI_TEST_CLASS_DECLARATION(test_7861)
GUI_TEST_CLASS_DECLARATION(test_7863)

#undef GUI_TEST_SUITE

}  // namespace GUITest_regression_scenarios

}  // namespace U2
